[2023-11-08T21:37:10.912+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: recalls_etl_v1.load_data_to_db manual__2023-11-08T21:37:02.153746+00:00 [queued]>
[2023-11-08T21:37:10.922+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: recalls_etl_v1.load_data_to_db manual__2023-11-08T21:37:02.153746+00:00 [queued]>
[2023-11-08T21:37:10.922+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-08T21:37:10.942+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_data_to_db> on 2023-11-08 21:37:02.153746+00:00
[2023-11-08T21:37:10.948+0000] {standard_task_runner.py:57} INFO - Started process 212 to run task
[2023-11-08T21:37:10.951+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'recalls_etl_v1', 'load_data_to_db', 'manual__2023-11-08T21:37:02.153746+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/recalls_etl_v1.py', '--cfg-path', '/tmp/tmpp0_0gecx']
[2023-11-08T21:37:10.952+0000] {standard_task_runner.py:85} INFO - Job 40: Subtask load_data_to_db
[2023-11-08T21:37:11.015+0000] {task_command.py:416} INFO - Running <TaskInstance: recalls_etl_v1.load_data_to_db manual__2023-11-08T21:37:02.153746+00:00 [running]> on host d2f41c2a3488
[2023-11-08T21:37:11.178+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='recalls_etl_v1' AIRFLOW_CTX_TASK_ID='load_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2023-11-08T21:37:02.153746+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-08T21:37:02.153746+00:00'
[2023-11-08T21:37:12.762+0000] {logging_mixin.py:151} INFO - Success: Loaded 29232 recall records to recalls_db.
[2023-11-08T21:37:12.763+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-08T21:37:12.774+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=recalls_etl_v1, task_id=load_data_to_db, execution_date=20231108T213702, start_date=20231108T213710, end_date=20231108T213712
[2023-11-08T21:37:12.810+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-08T21:37:12.830+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
